/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// WriteDeviceResourceRequest struct for WriteDeviceResourceRequest
type WriteDeviceResourceRequest struct {
	Value *WriteDeviceResourceRequestValue `json:"value,omitempty"`
}

// NewWriteDeviceResourceRequest instantiates a new WriteDeviceResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewWriteDeviceResourceRequest() *WriteDeviceResourceRequest {
	this := WriteDeviceResourceRequest{}
	return &this
}

// NewWriteDeviceResourceRequestWithDefaults instantiates a new WriteDeviceResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewWriteDeviceResourceRequestWithDefaults() *WriteDeviceResourceRequest {
	this := WriteDeviceResourceRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *WriteDeviceResourceRequest) GetValue() WriteDeviceResourceRequestValue {
	if o == nil || o.Value == nil {
		var ret WriteDeviceResourceRequestValue
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *WriteDeviceResourceRequest) GetValueOk() (*WriteDeviceResourceRequestValue, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *WriteDeviceResourceRequest) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given WriteDeviceResourceRequestValue and assigns it to the Value field.
func (o *WriteDeviceResourceRequest) SetValue(v WriteDeviceResourceRequestValue) {
	o.Value = &v
}

func (o WriteDeviceResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableWriteDeviceResourceRequest struct {
	value *WriteDeviceResourceRequest
	isSet bool
}

func (v NullableWriteDeviceResourceRequest) Get() *WriteDeviceResourceRequest {
	return v.value
}

func (v *NullableWriteDeviceResourceRequest) Set(val *WriteDeviceResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableWriteDeviceResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableWriteDeviceResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableWriteDeviceResourceRequest(val *WriteDeviceResourceRequest) *NullableWriteDeviceResourceRequest {
	return &NullableWriteDeviceResourceRequest{value: val, isSet: true}
}

func (v NullableWriteDeviceResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableWriteDeviceResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


