/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// LagoonDashboardPermissionsUpdatingRequestPermissionsInner struct for LagoonDashboardPermissionsUpdatingRequestPermissionsInner
type LagoonDashboardPermissionsUpdatingRequestPermissionsInner struct {
	Permission *string `json:"permission,omitempty"`
	UserId *int64 `json:"userId,omitempty"`
}

// NewLagoonDashboardPermissionsUpdatingRequestPermissionsInner instantiates a new LagoonDashboardPermissionsUpdatingRequestPermissionsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewLagoonDashboardPermissionsUpdatingRequestPermissionsInner() *LagoonDashboardPermissionsUpdatingRequestPermissionsInner {
	this := LagoonDashboardPermissionsUpdatingRequestPermissionsInner{}
	return &this
}

// NewLagoonDashboardPermissionsUpdatingRequestPermissionsInnerWithDefaults instantiates a new LagoonDashboardPermissionsUpdatingRequestPermissionsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewLagoonDashboardPermissionsUpdatingRequestPermissionsInnerWithDefaults() *LagoonDashboardPermissionsUpdatingRequestPermissionsInner {
	this := LagoonDashboardPermissionsUpdatingRequestPermissionsInner{}
	return &this
}

// GetPermission returns the Permission field value if set, zero value otherwise.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) GetPermission() string {
	if o == nil || o.Permission == nil {
		var ret string
		return ret
	}
	return *o.Permission
}

// GetPermissionOk returns a tuple with the Permission field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) GetPermissionOk() (*string, bool) {
	if o == nil || o.Permission == nil {
		return nil, false
	}
	return o.Permission, true
}

// HasPermission returns a boolean if a field has been set.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) HasPermission() bool {
	if o != nil && o.Permission != nil {
		return true
	}

	return false
}

// SetPermission gets a reference to the given string and assigns it to the Permission field.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) SetPermission(v string) {
	o.Permission = &v
}

// GetUserId returns the UserId field value if set, zero value otherwise.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) GetUserId() int64 {
	if o == nil || o.UserId == nil {
		var ret int64
		return ret
	}
	return *o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) GetUserIdOk() (*int64, bool) {
	if o == nil || o.UserId == nil {
		return nil, false
	}
	return o.UserId, true
}

// HasUserId returns a boolean if a field has been set.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) HasUserId() bool {
	if o != nil && o.UserId != nil {
		return true
	}

	return false
}

// SetUserId gets a reference to the given int64 and assigns it to the UserId field.
func (o *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) SetUserId(v int64) {
	o.UserId = &v
}

func (o LagoonDashboardPermissionsUpdatingRequestPermissionsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Permission != nil {
		toSerialize["permission"] = o.Permission
	}
	if o.UserId != nil {
		toSerialize["userId"] = o.UserId
	}
	return json.Marshal(toSerialize)
}

type NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner struct {
	value *LagoonDashboardPermissionsUpdatingRequestPermissionsInner
	isSet bool
}

func (v NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) Get() *LagoonDashboardPermissionsUpdatingRequestPermissionsInner {
	return v.value
}

func (v *NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) Set(val *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner(val *LagoonDashboardPermissionsUpdatingRequestPermissionsInner) *NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner {
	return &NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner{value: val, isSet: true}
}

func (v NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableLagoonDashboardPermissionsUpdatingRequestPermissionsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


