/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ExecuteDeviceResourceRequest struct for ExecuteDeviceResourceRequest
type ExecuteDeviceResourceRequest struct {
	Value *string `json:"value,omitempty"`
}

// NewExecuteDeviceResourceRequest instantiates a new ExecuteDeviceResourceRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewExecuteDeviceResourceRequest() *ExecuteDeviceResourceRequest {
	this := ExecuteDeviceResourceRequest{}
	return &this
}

// NewExecuteDeviceResourceRequestWithDefaults instantiates a new ExecuteDeviceResourceRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewExecuteDeviceResourceRequestWithDefaults() *ExecuteDeviceResourceRequest {
	this := ExecuteDeviceResourceRequest{}
	return &this
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ExecuteDeviceResourceRequest) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ExecuteDeviceResourceRequest) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ExecuteDeviceResourceRequest) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ExecuteDeviceResourceRequest) SetValue(v string) {
	o.Value = &v
}

func (o ExecuteDeviceResourceRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableExecuteDeviceResourceRequest struct {
	value *ExecuteDeviceResourceRequest
	isSet bool
}

func (v NullableExecuteDeviceResourceRequest) Get() *ExecuteDeviceResourceRequest {
	return v.value
}

func (v *NullableExecuteDeviceResourceRequest) Set(val *ExecuteDeviceResourceRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableExecuteDeviceResourceRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableExecuteDeviceResourceRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableExecuteDeviceResourceRequest(val *ExecuteDeviceResourceRequest) *NullableExecuteDeviceResourceRequest {
	return &NullableExecuteDeviceResourceRequest{value: val, isSet: true}
}

func (v NullableExecuteDeviceResourceRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableExecuteDeviceResourceRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


