/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// SoraCamVideoExportSpecification struct for SoraCamVideoExportSpecification
type SoraCamVideoExportSpecification struct {
	// エクスポート対象の開始時刻 (UNIX 時間 (ミリ秒))
	From int64 `json:"from"`
	// エクスポート対象の終了時刻 (UNIX 時間 (ミリ秒))  - 一回の API 呼び出しでエクスポートできる時間は最大 300 秒 (5 分) です。`from` と `to` の差が、300 秒を超えないようにしてください。 
	To int64 `json:"to"`
}

// NewSoraCamVideoExportSpecification instantiates a new SoraCamVideoExportSpecification object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoraCamVideoExportSpecification(from int64, to int64) *SoraCamVideoExportSpecification {
	this := SoraCamVideoExportSpecification{}
	this.From = from
	this.To = to
	return &this
}

// NewSoraCamVideoExportSpecificationWithDefaults instantiates a new SoraCamVideoExportSpecification object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoraCamVideoExportSpecificationWithDefaults() *SoraCamVideoExportSpecification {
	this := SoraCamVideoExportSpecification{}
	return &this
}

// GetFrom returns the From field value
func (o *SoraCamVideoExportSpecification) GetFrom() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.From
}

// GetFromOk returns a tuple with the From field value
// and a boolean to check if the value has been set.
func (o *SoraCamVideoExportSpecification) GetFromOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.From, true
}

// SetFrom sets field value
func (o *SoraCamVideoExportSpecification) SetFrom(v int64) {
	o.From = v
}

// GetTo returns the To field value
func (o *SoraCamVideoExportSpecification) GetTo() int64 {
	if o == nil {
		var ret int64
		return ret
	}

	return o.To
}

// GetToOk returns a tuple with the To field value
// and a boolean to check if the value has been set.
func (o *SoraCamVideoExportSpecification) GetToOk() (*int64, bool) {
	if o == nil {
		return nil, false
	}
	return &o.To, true
}

// SetTo sets field value
func (o *SoraCamVideoExportSpecification) SetTo(v int64) {
	o.To = v
}

func (o SoraCamVideoExportSpecification) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["from"] = o.From
	}
	if true {
		toSerialize["to"] = o.To
	}
	return json.Marshal(toSerialize)
}

type NullableSoraCamVideoExportSpecification struct {
	value *SoraCamVideoExportSpecification
	isSet bool
}

func (v NullableSoraCamVideoExportSpecification) Get() *SoraCamVideoExportSpecification {
	return v.value
}

func (v *NullableSoraCamVideoExportSpecification) Set(val *SoraCamVideoExportSpecification) {
	v.value = val
	v.isSet = true
}

func (v NullableSoraCamVideoExportSpecification) IsSet() bool {
	return v.isSet
}

func (v *NullableSoraCamVideoExportSpecification) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoraCamVideoExportSpecification(val *SoraCamVideoExportSpecification) *NullableSoraCamVideoExportSpecification {
	return &NullableSoraCamVideoExportSpecification{value: val, isSet: true}
}

func (v NullableSoraCamVideoExportSpecification) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoraCamVideoExportSpecification) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


