/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// SoraCamLicensePackResponse struct for SoraCamLicensePackResponse
type SoraCamLicensePackResponse struct {
	// ライセンスパックの ID
	Id *string `json:"id,omitempty"`
	// ライセンスパックの名前
	Name *string `json:"name,omitempty"`
	// 現在のライセンス数
	Quantity *int32 `json:"quantity,omitempty"`
	// ライセンスパックの販売元
	SalesChannel *string `json:"salesChannel,omitempty"`
}

// NewSoraCamLicensePackResponse instantiates a new SoraCamLicensePackResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSoraCamLicensePackResponse() *SoraCamLicensePackResponse {
	this := SoraCamLicensePackResponse{}
	return &this
}

// NewSoraCamLicensePackResponseWithDefaults instantiates a new SoraCamLicensePackResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSoraCamLicensePackResponseWithDefaults() *SoraCamLicensePackResponse {
	this := SoraCamLicensePackResponse{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *SoraCamLicensePackResponse) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraCamLicensePackResponse) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *SoraCamLicensePackResponse) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *SoraCamLicensePackResponse) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *SoraCamLicensePackResponse) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraCamLicensePackResponse) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *SoraCamLicensePackResponse) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *SoraCamLicensePackResponse) SetName(v string) {
	o.Name = &v
}

// GetQuantity returns the Quantity field value if set, zero value otherwise.
func (o *SoraCamLicensePackResponse) GetQuantity() int32 {
	if o == nil || o.Quantity == nil {
		var ret int32
		return ret
	}
	return *o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraCamLicensePackResponse) GetQuantityOk() (*int32, bool) {
	if o == nil || o.Quantity == nil {
		return nil, false
	}
	return o.Quantity, true
}

// HasQuantity returns a boolean if a field has been set.
func (o *SoraCamLicensePackResponse) HasQuantity() bool {
	if o != nil && o.Quantity != nil {
		return true
	}

	return false
}

// SetQuantity gets a reference to the given int32 and assigns it to the Quantity field.
func (o *SoraCamLicensePackResponse) SetQuantity(v int32) {
	o.Quantity = &v
}

// GetSalesChannel returns the SalesChannel field value if set, zero value otherwise.
func (o *SoraCamLicensePackResponse) GetSalesChannel() string {
	if o == nil || o.SalesChannel == nil {
		var ret string
		return ret
	}
	return *o.SalesChannel
}

// GetSalesChannelOk returns a tuple with the SalesChannel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SoraCamLicensePackResponse) GetSalesChannelOk() (*string, bool) {
	if o == nil || o.SalesChannel == nil {
		return nil, false
	}
	return o.SalesChannel, true
}

// HasSalesChannel returns a boolean if a field has been set.
func (o *SoraCamLicensePackResponse) HasSalesChannel() bool {
	if o != nil && o.SalesChannel != nil {
		return true
	}

	return false
}

// SetSalesChannel gets a reference to the given string and assigns it to the SalesChannel field.
func (o *SoraCamLicensePackResponse) SetSalesChannel(v string) {
	o.SalesChannel = &v
}

func (o SoraCamLicensePackResponse) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Quantity != nil {
		toSerialize["quantity"] = o.Quantity
	}
	if o.SalesChannel != nil {
		toSerialize["salesChannel"] = o.SalesChannel
	}
	return json.Marshal(toSerialize)
}

type NullableSoraCamLicensePackResponse struct {
	value *SoraCamLicensePackResponse
	isSet bool
}

func (v NullableSoraCamLicensePackResponse) Get() *SoraCamLicensePackResponse {
	return v.value
}

func (v *NullableSoraCamLicensePackResponse) Set(val *SoraCamLicensePackResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableSoraCamLicensePackResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableSoraCamLicensePackResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSoraCamLicensePackResponse(val *SoraCamLicensePackResponse) *NullableSoraCamLicensePackResponse {
	return &NullableSoraCamLicensePackResponse{value: val, isSet: true}
}

func (v NullableSoraCamLicensePackResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSoraCamLicensePackResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


