/*
SORACOM API

SORACOM API v1

API version: VERSION_PLACEHOLDER
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapiclient

import (
	"encoding/json"
)

// ResourceSummaryItemDimension struct for ResourceSummaryItemDimension
type ResourceSummaryItemDimension struct {
	// リソースの要約アイテムのディメンションの名前
	Name *string `json:"name,omitempty"`
	// リソースの要約アイテムのディメンションの値
	Value *string `json:"value,omitempty"`
}

// NewResourceSummaryItemDimension instantiates a new ResourceSummaryItemDimension object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResourceSummaryItemDimension() *ResourceSummaryItemDimension {
	this := ResourceSummaryItemDimension{}
	return &this
}

// NewResourceSummaryItemDimensionWithDefaults instantiates a new ResourceSummaryItemDimension object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResourceSummaryItemDimensionWithDefaults() *ResourceSummaryItemDimension {
	this := ResourceSummaryItemDimension{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *ResourceSummaryItemDimension) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceSummaryItemDimension) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *ResourceSummaryItemDimension) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *ResourceSummaryItemDimension) SetName(v string) {
	o.Name = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResourceSummaryItemDimension) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResourceSummaryItemDimension) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResourceSummaryItemDimension) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ResourceSummaryItemDimension) SetValue(v string) {
	o.Value = &v
}

func (o ResourceSummaryItemDimension) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	return json.Marshal(toSerialize)
}

type NullableResourceSummaryItemDimension struct {
	value *ResourceSummaryItemDimension
	isSet bool
}

func (v NullableResourceSummaryItemDimension) Get() *ResourceSummaryItemDimension {
	return v.value
}

func (v *NullableResourceSummaryItemDimension) Set(val *ResourceSummaryItemDimension) {
	v.value = val
	v.isSet = true
}

func (v NullableResourceSummaryItemDimension) IsSet() bool {
	return v.isSet
}

func (v *NullableResourceSummaryItemDimension) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResourceSummaryItemDimension(val *ResourceSummaryItemDimension) *NullableResourceSummaryItemDimension {
	return &NullableResourceSummaryItemDimension{value: val, isSet: true}
}

func (v NullableResourceSummaryItemDimension) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResourceSummaryItemDimension) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


