name: test

on: [push]

jobs:
  test:
    strategy:
      matrix:
        platform: [ubuntu-latest]
        go-version: [1.19.x]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # to retrieve git tags
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Run CI test
        run: make ci-test GOPATH=/home/runner/go
